_lootWeapons =
[

	"hgun_ACPC2_F",
	"hgun_P07_F",
	"hgun_Pistol_heavy_01_F",
	"hgun_Pistol_heavy_02_F",
	"hgun_Rook40_F",
	//

	"hgun_PDW2000_F",
	"SMG_01_F",
	"SMG_02_F",
	//
	"hgun_PDW2000_F",
	"SMG_01_F",
	"SMG_02_F",
	//
	"hgun_PDW2000_F",
	"SMG_01_F",
	"SMG_02_F",
	//
	"hgun_PDW2000_F",
	"SMG_01_F",
	"SMG_02_F",
	//
	"arifle_Katiba_C_F",
	"arifle_Katiba_F",
	"arifle_Katiba_GL_F",
	"arifle_Mk20_F",
	"arifle_Mk20_GL_F",
	"arifle_Mk20_GL_plain_F",
	"arifle_Mk20_plain_F",
	"arifle_Mk20C_F",
	"arifle_Mk20C_plain_F",
	"arifle_MX_Black_F",
	"arifle_MX_F",
	"arifle_MX_GL_Black_F",
	"arifle_MX_GL_F",
	"arifle_MXC_Black_F",
	"arifle_MXC_F",
	"arifle_SDAR_F",
	"arifle_TRG20_F",
	"arifle_TRG21_F",
	"arifle_TRG21_GL_F",
	//
	"arifle_Katiba_C_F",
	"arifle_Katiba_F",
	"arifle_Katiba_GL_F",
	"arifle_Mk20_F",
	"arifle_Mk20_GL_F",
	"arifle_Mk20_GL_plain_F",
	"arifle_Mk20_plain_F",
	"arifle_Mk20C_F",
	"arifle_Mk20C_plain_F",
	"arifle_MX_Black_F",
	"arifle_MX_F",
	"arifle_MX_GL_Black_F",
	"arifle_MX_GL_F",
	"arifle_MXC_Black_F",
	"arifle_MXC_F",
	"arifle_SDAR_F",
	"arifle_TRG20_F",
	"arifle_TRG21_F",
	"arifle_TRG21_GL_F",
	"arifle_MX_SW_Black_F",
	"arifle_MX_SW_F",
	"LMG_Mk200_F",
	"arifle_MXM_Black_F",
	"arifle_MXM_F",
	"srifle_DMR_01_F",
	"srifle_EBR_F",
	"srifle_DMR_06_camo_F",
	"srifle_DMR_06_olive_F",
	"srifle_DMR_03_khaki_F",
	"srifle_DMR_03_multicam_F",
	"srifle_DMR_03_tan_F",
	"srifle_DMR_03_woodland_F",
	"MMG_01_hex_F",
	"MMG_01_tan_F",
	"MMG_02_camo_F",
	"MMG_02_black_F",
	"MMG_02_sand_F",
	"LMG_Zafir_F",
	"srifle_GM6_camo_F",
	"srifle_GM6_F",
	"srifle_LRR_camo_F",
	"srifle_LRR_F",
	"srifle_DMR_03_F",
	"srifle_DMR_04_F",
	"srifle_DMR_04_Tan_F",
	"srifle_DMR_02_camo_F",
	"srifle_DMR_02_F",
	"srifle_DMR_02_sniper_F",
	"srifle_DMR_05_blk_F",
	"srifle_DMR_05_hex_F",
	"srifle_DMR_05_tan_f",
	"Exile_Weapon_AK107",
	"Exile_Weapon_AK107_GL",
	"Exile_Weapon_AK74",
	"Exile_Weapon_AK74_GL",
	"Exile_Weapon_AK47",
	"Exile_Weapon_AKM",
	"Exile_Weapon_AKS",
	"Exile_Weapon_AKS_Gold",
	"Exile_Weapon_CZ550",
	"Exile_Weapon_SVD",
	"Exile_Weapon_SVDCamo",
	"Exile_Weapon_VSSVintorez",
	"Exile_Weapon_DMR",
	"Exile_Weapon_LeeEnfield",
	// APEX
	"SMG_05_F",
	"LMG_03_F",
	"arifle_MX_khk_F",
	"arifle_MX_GL_khk_F",
	"arifle_MXC_khk_F",
	"arifle_MXM_khk_F",
	"srifle_LRR_tna_F",
	"srifle_GM6_ghex_F",
	"srifle_DMR_07_blk_F",
	"srifle_DMR_07_hex_F",
	"srifle_DMR_07_ghex_F",
	"arifle_AK12_F",
	"arifle_AK12_GL_F",
	"arifle_AKM_F",
	"arifle_AKM_FL_F",
	"arifle_AKS_F",
	"arifle_ARX_blk_F",
	"arifle_ARX_ghex_F",
	"arifle_ARX_hex_F",
	"arifle_CTAR_blk_F",
	"arifle_CTAR_hex_F",
	"arifle_CTAR_ghex_F",
	"arifle_CTAR_GL_blk_F",
	"arifle_CTARS_blk_F",
	"arifle_CTARS_ghex_F",
	"arifle_CTARS_hex_F",
	"arifle_SPAR_01_blk_F",
	"arifle_SPAR_01_khk_F",
	"arifle_SPAR_01_snd_F",
	"arifle_SPAR_01_GL_blk_F",
	"arifle_SPAR_01_GL_khk_F",
	"arifle_SPAR_01_GL_snd_F",
	"arifle_SPAR_02_blk_F",
	"arifle_SPAR_02_khk_F",
	"arifle_SPAR_02_snd_F",
	"arifle_SPAR_03_blk_F",
	"arifle_SPAR_03_khk_F",
	"arifle_SPAR_03_snd_F"

];

_weapon = selectRandom _lootWeapons;

_weaponItem =

[
	"optic_Aco",
	"optic_ACO_grn",
	"optic_ACO_grn_smg",
	"optic_Aco_smg",
	"optic_AMS",
	"optic_AMS_khk",
	"optic_AMS_snd",
	"optic_Arco",
	"optic_DMS",
	"optic_Hamr",
	"optic_Holosight",
	"optic_Holosight_smg",
	"optic_KHS_blk",
	"optic_KHS_hex",
	"optic_KHS_old",
	"optic_KHS_tan",
	"optic_LRPS",
	"optic_MRCO",
	"optic_MRD",
	//Apex
	"optic_Arco_blk_F",
	"optic_Arco_ghex_F",
	"optic_DMS_ghex_F",
	"optic_Hamr_khk_F",
	"optic_ERCO_blk_F",
	"optic_ERCO_khk_F",
	"optic_ERCO_snd_F",
	"optic_SOS_khk_F",
	"optic_LRPS_tna_F",
	"optic_LRPS_ghex_F",
	"optic_Holosight_blk_F",
	"optic_Holosight_khk_F",
	"optic_Holosight_smg_blk_F"
];


_attachment = selectRandom _weaponItem;

_uniforms =
[

	"U_C_HunterBody_grn",
	"U_IG_Guerilla1_1",
	"U_IG_Guerilla2_1",
	"U_IG_Guerilla2_2",
	"U_IG_Guerilla2_3",
	"U_IG_Guerilla3_1",
	"U_BG_Guerilla2_1",
	"U_IG_Guerilla3_2",
	"U_BG_Guerrilla_6_1",
	"U_BG_Guerilla1_1",
	"U_BG_Guerilla2_2",
	"U_BG_Guerilla2_3",
	"U_BG_Guerilla3_1",
	"U_BG_leader",
	"U_IG_leader",
	"U_I_G_resistanceLeader_F"
];

_uniform = selectRandom _uniforms;

_vests =

[

	"V_BandollierB_blk",
	"V_BandollierB_cbr",
	"V_BandollierB_khk",
	"V_BandollierB_oli",
	"V_BandollierB_rgr",
	"V_Press_F",
	"V_Rangemaster_belt",
	"V_TacVest_blk",
	"V_TacVest_blk_POLICE",
	"V_TacVest_brn",
	"V_TacVest_camo",
	"V_TacVest_khk",
	"V_TacVest_oli",
	"V_TacVestCamo_khk",
	"V_TacVestIR_blk",
	"V_I_G_resistanceLeader_F",
	"V_Chestrig_blk",
	"V_Chestrig_khk",
	"V_Chestrig_oli",
	"V_Chestrig_rgr",
	"V_HarnessO_brn",
	"V_HarnessO_gry",
	"V_HarnessOGL_brn",
	"V_HarnessOGL_gry",
	"V_HarnessOSpec_brn",
	"V_HarnessOSpec_gry"

];

_vest = selectRandom _vests;

_backPacks =
[

	"B_HuntingBackpack",
	"B_OutdoorPack_blk",
	"B_OutdoorPack_blu",
	"B_OutdoorPack_tan",
	"B_AssaultPack_blk",
	"B_AssaultPack_cbr",
	"B_AssaultPack_dgtl",
	"B_AssaultPack_khk",
	"B_AssaultPack_mcamo",
	"B_AssaultPack_rgr",
	"B_AssaultPack_sgg",
	"B_FieldPack_blk",
	"B_FieldPack_cbr",
	"B_FieldPack_ocamo",
	"B_FieldPack_oucamo",
	"B_TacticalPack_blk",
	"B_TacticalPack_rgr",
	"B_TacticalPack_ocamo",
	"B_TacticalPack_mcamo",
	"B_TacticalPack_oli",
	"B_Kitbag_cbr",
	"B_Kitbag_mcamo",
	"B_Kitbag_sgg",
	"B_Bergen_blk",
	"B_Bergen_mcamo",
	"B_Bergen_rgr",
	"B_Bergen_sgg",
	"B_Carryall_cbr",
	"B_Carryall_khk",
	"B_Carryall_mcamo",
	"B_Carryall_ocamo",
	"B_Carryall_oli",
	"B_Carryall_oucamo"

];

_backpack = selectRandom _backPacks;

_items =
[

	"Chemlight_blue",
	"Chemlight_green",
	"Chemlight_red",
	"FlareGreen_F",
	"FlareRed_F",
	"FlareWhite_F",
	"FlareYellow_F",
	"UGL_FlareGreen_F",
	"UGL_FlareRed_F",
	"UGL_FlareWhite_F",
	"UGL_FlareYellow_F",
	"3Rnd_UGL_FlareGreen_F",
	"3Rnd_UGL_FlareRed_F",
	"3Rnd_UGL_FlareWhite_F",
	"3Rnd_UGL_FlareYellow_F",
	"HandGrenade",
	"MiniGrenade",
	"B_IR_Grenade",
	"O_IR_Grenade",
	"I_IR_Grenade",
	"1Rnd_HE_Grenade_shell",
	"3Rnd_HE_Grenade_shell",
	"Exile_Item_EMRE",		
	"Exile_Item_GloriousKnakworst",
	"Exile_Item_Surstromming",
	"Exile_Item_SausageGravy",
	"Exile_Item_Catfood",
	"Exile_Item_ChristmasTinner",
	"Exile_Item_BBQSandwich",
	"Exile_Item_Dogfood",
	"Exile_Item_BeefParts",
	"Exile_Item_Cheathas",
	"Exile_Item_Noodles",
	"Exile_Item_SeedAstics",
	"Exile_Item_Raisins",
	"Exile_Item_Moobar",
	"Exile_Item_InstantCoffee",
	"Exile_Item_PlasticBottleCoffee",
	"Exile_Item_PowerDrink",
	"Exile_Item_PlasticBottleFreshWater",
	"Exile_Item_Beer",
	"Exile_Item_EnergyDrink",
	"Exile_Item_ChocolateMilk",
	"Exile_Item_MountainDupe",
	"Exile_Item_PlasticBottleEmpty",
	"Exile_Item_InstaDoc",
	"Exile_Item_Bandage",
	"Exile_Item_Vishpirin",
	"Exile_Item_Heatpack",
	"Exile_Item_CodeLock"

];

_item = selectRandom _items;

_gear = [_weapon,_attachment,_uniform,_vest,_backpack,_item];
_gear